version: '3'

services:
  postgres:
    container_name: postgres-db
    image: postgres:9.6.6
    ports: 
      - 5432:5432
    volumes:
      - ./pgdb:/var/lib/postgresql/data
    restart: always
    env_file: .env
    environment:
      - LC_ALL=C.UTF-8


  redis:
    image: redis:3.0.6
    restart: "on-failure"
    container_name: redis
    ports:
      - 6379:6379
    volumes:
      - ./redisdb:/var/lib/redis


  celery:
    restart: "always"
    build:
      context: .
      dockerfile: celery.dockerfile
    container_name: celery
    env_file: .env
    command: /venv/bin/celery --app=todo_application.celery:app worker -B --loglevel=INFO
    volumes:
      - .:/src
    links:
      - redis
      - postgres
    depends_on:
      - "redis"
      - "postgres"


  web:
    container_name: todo
    build: .
    restart: "always"
    command: python3 manage.py runserver 0.0.0.0:8000
    env_file: .env
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - "postgres"

