# Generated by Django 2.1.2 on 2018-10-27 22:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SharingTasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sharing_type', models.CharField(choices=[('v', 'View'), ('vr', 'View & Write Review')], max_length=2, verbose_name='Sharing Type')),
            ],
        ),
        migrations.CreateModel(
            name='TaskReviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.TextField(help_text='You must write here task your review', verbose_name='Review')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('ord', models.PositiveIntegerField(default=1, verbose_name='Ord')),
                ('is_published', models.BooleanField(default=True, verbose_name='Is Published')),
            ],
        ),
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='You must write here task title', max_length=100, verbose_name='Title')),
                ('slug', models.SlugField(editable=False, max_length=100, null=True, verbose_name='Slug')),
                ('description', models.TextField(help_text='You must write here task description', verbose_name='Description')),
                ('deadline', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Deadline')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('ord', models.PositiveIntegerField(default=1, verbose_name='Ord')),
                ('is_published', models.BooleanField(default=True, verbose_name='Is Published')),
            ],
            options={
                'verbose_name': 'Task',
                'verbose_name_plural': 'Tasks',
                'ordering': ('-created',),
            },
        ),
    ]
