# Generated by Django 2.1.2 on 2018-10-27 22:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0002_auto_20181028_0230'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sharingtasks',
            options={'verbose_name': 'Sharing Task', 'verbose_name_plural': 'Sharing Tasks'},
        ),
        migrations.AlterModelOptions(
            name='taskreviews',
            options={'ordering': ('-created',), 'verbose_name': 'Task Review', 'verbose_name_plural': 'Task Reviews'},
        ),
        migrations.AddField(
            model_name='tasks',
            name='performer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='performer_tasks', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tasks',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creator_tasks', to=settings.AUTH_USER_MODEL),
        ),
    ]
