# Generated by Django 2.1.2 on 2018-10-29 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_auto_20181028_0239'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasks',
            name='performer',
        ),
    ]
