# Generated by Django 2.1.2 on 2018-10-29 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_remove_tasks_performer'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='status',
            field=models.CharField(choices=[('s', 'Stating'), ('r', 'Running'), ('c', 'Complated')], default=1, max_length=1, verbose_name='Status'),
            preserve_default=False,
        ),
    ]
